#!/bin/sh

diff=`git diff --name-only HEAD@{1} HEAD`

migrate=`expr "$diff" : ".*db/migrate.*"`
bundle=`expr "$diff" : ".*Gemfile*"`

if [ ! "$bundle" -eq 0 ]
then
    echo ""
    echo "###################################"
    echo "#  Changes in Gemfile detected!   #"
    echo "# You should run 'bundle install' #"
    echo "###################################"
    echo ""
fi

if [ ! "$migrate" -eq 0 ]
then
    echo ""
    echo "####################################"
    echo "#     Migration file detected!     #"
    echo "# You should run 'rake db:migrate' #"
    echo "####################################"
    echo ""
fi
